language: php

php:
  - 5.5
  - 5.6
  - 7.0

sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - pip install --user codecov

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.1.1"
  - travis_retry composer update --dev --prefer-dist --no-interaction

before_script:
  - chmod -R a+w runtime
  - mysql -e 'create database bootstrap_yii2_tests;'
  - php yii create-local-config/init --path=@app/config/local/config.php
  - composer test-prepare
  - composer test-build

script:
  - composer exec codecept run -- --report --coverage-xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml

after_success:
  - codecov
