language: php

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - pip install --user codecov

install:
  - composer self-update && composer --version
  - composer global require "fxp/composer-asset-plugin:~1.1.1"
  - composer install

before_script:
  - chmod -R a+w runtime
  - mysql -e 'create database bootstrap_yii2_tests;'
  - php yii create-local-config --path=@app/config/local/main.php
  - composer build:test

script:
  - vendor/bin/codecept run --report --coverage-xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml

after_success:
  - codecov
