version: '2'

services:
  php:
    image: rkit/docker-phpstack:7.1
    expose:
      - 9000
    links:
      - mysql:mysql
    volumes:
      - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./:/var/www/app

  nginx:
    image: nginx:1.12.0
    ports:
      - "80:80"
    links:
      - php
    volumes:
      - ./docker/nginx/conf.d/${NGINX_CONFIG}:/etc/nginx/conf.d/${NGINX_CONFIG}
      - ./:/var/www/app

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - data-mysql-5.7:/var/lib/mysql
    restart: always
    env_file: .env

volumes:
  data-mysql-5.7:
    driver: local
